name: Daily News Fetch

on:
  schedule:
    - cron: '00 18 * * *'


permissions:
  contents: write
  issues: read

jobs:
  fetch-and-append-news:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # This token is required to push changes back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the script
        run: python trend.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add trends.csv
          git commit -m "Update temperature data" || echo "No changes to commit"
          git push
